# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1435/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1435/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lucas/Documentos/trabalho/trabalho-de-grafos

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lucas/Documentos/trabalho/trabalho-de-grafos

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/snap/cmake/1435/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1435/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucas/Documentos/trabalho/trabalho-de-grafos/CMakeFiles /home/lucas/Documentos/trabalho/trabalho-de-grafos//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucas/Documentos/trabalho/trabalho-de-grafos/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main.out

# Build rule for target.
main.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main.out
.PHONY : main.out

# fast build rule for target.
main.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/build
.PHONY : main.out/fast

src/grafo_lista.o: src/grafo_lista.cpp.o
.PHONY : src/grafo_lista.o

# target to build an object file
src/grafo_lista.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/src/grafo_lista.cpp.o
.PHONY : src/grafo_lista.cpp.o

src/grafo_lista.i: src/grafo_lista.cpp.i
.PHONY : src/grafo_lista.i

# target to preprocess a source file
src/grafo_lista.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/src/grafo_lista.cpp.i
.PHONY : src/grafo_lista.cpp.i

src/grafo_lista.s: src/grafo_lista.cpp.s
.PHONY : src/grafo_lista.s

# target to generate assembly for a file
src/grafo_lista.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/src/grafo_lista.cpp.s
.PHONY : src/grafo_lista.cpp.s

src/grafo_matriz.o: src/grafo_matriz.cpp.o
.PHONY : src/grafo_matriz.o

# target to build an object file
src/grafo_matriz.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/src/grafo_matriz.cpp.o
.PHONY : src/grafo_matriz.cpp.o

src/grafo_matriz.i: src/grafo_matriz.cpp.i
.PHONY : src/grafo_matriz.i

# target to preprocess a source file
src/grafo_matriz.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/src/grafo_matriz.cpp.i
.PHONY : src/grafo_matriz.cpp.i

src/grafo_matriz.s: src/grafo_matriz.cpp.s
.PHONY : src/grafo_matriz.s

# target to generate assembly for a file
src/grafo_matriz.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/src/grafo_matriz.cpp.s
.PHONY : src/grafo_matriz.cpp.s

src/lista_encadeada.o: src/lista_encadeada.cpp.o
.PHONY : src/lista_encadeada.o

# target to build an object file
src/lista_encadeada.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/src/lista_encadeada.cpp.o
.PHONY : src/lista_encadeada.cpp.o

src/lista_encadeada.i: src/lista_encadeada.cpp.i
.PHONY : src/lista_encadeada.i

# target to preprocess a source file
src/lista_encadeada.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/src/lista_encadeada.cpp.i
.PHONY : src/lista_encadeada.cpp.i

src/lista_encadeada.s: src/lista_encadeada.cpp.s
.PHONY : src/lista_encadeada.s

# target to generate assembly for a file
src/lista_encadeada.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/src/lista_encadeada.cpp.s
.PHONY : src/lista_encadeada.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main.out"
	@echo "... src/grafo_lista.o"
	@echo "... src/grafo_lista.i"
	@echo "... src/grafo_lista.s"
	@echo "... src/grafo_matriz.o"
	@echo "... src/grafo_matriz.i"
	@echo "... src/grafo_matriz.s"
	@echo "... src/lista_encadeada.o"
	@echo "... src/lista_encadeada.i"
	@echo "... src/lista_encadeada.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

